development:
  cloud_name: "dkeq1ghol"
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: "dkeq1ghol"
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_file_support: true
  
test:
  cloud_name: dkeq1ghol
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false